apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-php
  labels:
    app: nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
      tier: webserver
  template:
    metadata:
      labels:
        app: nginx-php
        tier: webserver
    spec:
      containers:
      - image: gcr.io/myage-ci-cd-k8s/myage@sha256:8844c5d42a45569a2526e27dcae3c09c512e4ae2dc687b627fbbf0bb5b67c08e
        name: nginx-php
        ports:
        - containerPort: 80
        