apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
  labels: 
    app: nginx-php
spec:
  ports:
    - port: 80
  selector:
    #pegar todos os pods criados pelo deployment.yaml
    #pelo nome que foi declarado lá
    app: nginx-php
    tier: webserver
  #k8s gerará loadbalancer gerando endpoints apontando para os pods criados
  type: LoadBalancer